cargo-features = ["profile-rustflags"]

[workspace]
resolver = "2"
members = [
    "fold",
    # "rtori-core-wgpu", 
    "rtori-core-simd",
    "rtori-server",
    # "rtori-cli",
    "rtori-os-fold-importer",
    "rtori-core",
    "rtori-core-ext",
    "rtori-os-model",
    "rtori-core-ffi"
]


[patch.crates-io]
diplomat = { git = 'https://github.com/aabizri/diplomat.git', branch = "feature-custom-allocators" }
diplomat-runtime = { git = 'https://github.com/aabizri/diplomat.git', branch = "feature-custom-allocators" }
diplomat_core = { git = 'https://github.com/aabizri/diplomat.git', branch = "feature-custom-allocators" }
diplomat-tool = { git = 'https://github.com/aabizri/diplomat.git', branch = "feature-custom-allocators" }

[profile.bench]
lto = true
codegen-units = 1
#rustflags = ["-C", "target-cpu=native"]
