#!/bin/env/bash

export DYLD_PRINT_APIS=1
export DYLD_PRINT_ENV=1
export DYLD_PRINT_OPS=1
export DYLD_PRINT_INITIALIZERS=1
export DYLD_PRINT_LIBRARIES=1
export DYLD_PRINT_LIBRARIES_POST_LAUNCH=1
export DYLD_PRINT_SEGMENTS=1
export DYLD_PRINT_STATISTICS=1

$@
